stack-name: autoscaling-demo
template-file-path: ./template.yaml
parameters:
  ProjectName: autoscaling-labWorkshop
  VpcCidr: 10.0.0.0/16
  PublicSubnet1Cidr: 10.0.1.0/24
  PublicSubnet2Cidr: 10.0.2.0/24
  PrivateSubnet1Cidr: 10.0.11.0/24
  PrivateSubnet2Cidr: 10.0.12.0/24
  InstanceType: t3.micro
  MinInstances: "1"
  DesiredInstances: "1"
  MaxInstances: "4"
  CpuScaleOutThreshold: "30"
tags:
  Project: autoscaling-lab
  ManagedBy: cloudformation-git-sync
  Environment: demo